name: CMake Linux Build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build-linux

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build-linux
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build-linux
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Launcher
          path: ${{github.workspace}}/build-linux/Release/BeamMP-Launcher
